name: build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
        id-token: write
        packages: write
        contents: write
    runs-on: ubuntu-latest
    steps:
        - name: Check out code
          uses: actions/checkout@v4
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.21'
        - name: Run Go build
          run: |
            go build -v -o bad-go ./...
        - name: Sign artifact
          uses: jhrozek/generate-build-provenance@0db1a8f8657a563a261f8bd6da3b1220e8e543ad
          with:
            subject-path: '${{ github.workspace }}/bad-go'
